// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvmO-wIdgHy8vjppMVeaXUkg2Bu3hfkU',
    appId: '1:906031249555:web:4d04336a4b22ad367bb566',
    messagingSenderId: '906031249555',
    projectId: 'mym-raktaveer-90ff3',
    authDomain: 'mym-raktaveer-90ff3.firebaseapp.com',
    storageBucket: 'mym-raktaveer-90ff3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbu6HinC23lmFfyBiZAChU3f6uk8ZXSYc',
    appId: '1:906031249555:android:701f2968ed7f63297bb566',
    messagingSenderId: '906031249555',
    projectId: 'mym-raktaveer-90ff3',
    storageBucket: 'mym-raktaveer-90ff3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8_tVzFi7IJVkXvEJ2nU5R_1v2AMWYV0',
    appId: '1:906031249555:ios:9cd11905d72830437bb566',
    messagingSenderId: '906031249555',
    projectId: 'mym-raktaveer-90ff3',
    storageBucket: 'mym-raktaveer-90ff3.appspot.com',
    iosBundleId: 'com.example.mymRaktaveerFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD8_tVzFi7IJVkXvEJ2nU5R_1v2AMWYV0',
    appId: '1:906031249555:ios:55c5450b3fe92cb87bb566',
    messagingSenderId: '906031249555',
    projectId: 'mym-raktaveer-90ff3',
    storageBucket: 'mym-raktaveer-90ff3.appspot.com',
    iosBundleId: 'com.example.mymRaktaveerFrontend.RunnerTests',
  );
}
